### ISSUE TITLE
Some IJ-OpenCV plugins require RGB image

### ISSUE THREAD

**Issue by ctrueden** [joheras/IJ-OpenCV#2]
The following macro:
```javascript
newImage("Untitled", "8-bit ramp", 64, 64, 1);
makeOval(16, 18, 35, 27);
setForegroundColor(255, 255, 255);
run("Fill", "slice");
run("Select None");
run("BlackHatJ ", "x=2 y=2");

```
Produces the exception:
```
(Fiji Is Just) ImageJ 2.0.0-rc-59/1.51j; Java 1.8.0_112 [64-bit]; Mac OS X 10.12.3; 125MB of 9795MB (1%)
 
java.lang.RuntimeException: /Users/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv-3.0.0/modules/imgproc/src/color.cpp:7564: error: (-215) scn == 3 || scn == 4 in function cvtColor

	at org.bytedeco.javacpp.opencv_imgproc.cvtColor(Native Method)
	at BlackHatJ_.run(BlackHatJ_.java:53)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
```

If you change `8-bit` to `RGB` (!) then it runs.

Is this because the BlackHatJ command [hardcodes the conversion from BGR to gray](https://github.com/joheras/IJ-OpenCV/blob/35ba670d2f413ef7f4089e2b48d8963be32791fd/src/main/java/ijopencv/examples/BlackHatJ_.java#L56)?

The same error with 8-bit images happens also with CannyEdgeDetectionJ, FaceDetectionJ, and probably others.

**Comment by ctrueden** [comment]
For RGB data, FaceDetectionJ says:
```
java.lang.RuntimeException: /Users/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv-3.0.0/modules/objdetect/src/cascadedetect.cpp:1634: error: (-215) !empty() in function detectMultiScale

	at org.bytedeco.javacpp.opencv_objdetect$CascadeClassifier.detectMultiScale(Native Method)
	at FaceDetectionJ_.detectFaces(FaceDetectionJ_.java:58)
	at FaceDetectionJ_.run(FaceDetectionJ_.java:38)
```

**Comment by joheras** [comment]
The FaceDetectionJ plugin needs an xml file to work.
This file is available at the following link:
https://github.com/joheras/IJ-OpenCV/blob/master/utils/haarcascade_frontalface_alt.xml
You need to download it and include it in the plugins folder of ImageJ.
Once that you do that, the plugin should work without problems.





2017-03-14 16:11 GMT+01:00 Curtis Rueden <notifications@github.com>:

**Comment by ctrueden** [comment]
> The FaceDetectionJ plugin needs an xml file to work.

Interesting. Would it make sense to embed it in the JAR file as a resource, and have the FaceDetectionJ plugin extract it? Or at least ship it on the IJ-OpenCV update site in the `plugins/` folder directly?

**Comment by joheras** [comment]
Following your advice I have embedded the xml in the JAR file as a
resource, and now it is not necessary to manually include the xml file in
the folder.
This new version of the plugin can be installed from the ImageJ updater.

2017-03-15 16:41 GMT+01:00 Curtis Rueden <notifications@github.com>:

**Comment by joheras** [comment]
Currently, the bridge between ImageJ and OpenCV only works with RGB images.
I have modified the plugins to proactively check for the correct type and
give a normal ImageJ error message when the type is incorrect. The new
version of the plugins can be downloaded using the ImageJ updater.
I will try to fix this issue as soon as possible.

2017-03-14 15:58 GMT+01:00 Curtis Rueden <notifications@github.com>:
