### ISSUE TITLE
[Error] Module threw Exception

### ISSUE THREAD

**Issue by rharkes** [joheras/IJ-OpenCV#23]
Dear Jónathan Heras,
When I try to run any of the OpenCV plugins I get the following error:
```
(Fiji Is Just) ImageJ 2.0.0-rc-71/1.52p; Java 1.8.0_172 [64-bit]; Windows 7 6.1; 149MB of 24449MB (<1%)
[ERROR] Module threw exception
java.lang.RuntimeException: OpenCV(3.4.2) c:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.2\modules\imgproc\src\color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'cv::CvtHelper<struct cv::Set<3,4,-1>,struct cv::Set<1,-1,-1>,struct cv::Set<0,2,5>,2>::CvtHelper'

	at org.bytedeco.javacpp.opencv_imgproc.cvtColor(Native Method)
	at com.mycompany.adaptivethresholdj.Adaptive_ThresholdJ_.run(Adaptive_ThresholdJ_.java:71)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by LauLauThom** [comment]
Hi,
Sorry for the issues, some plugins expects 8-bit images, and it looks like the error message means that the image type is not appropriate for this function.
Can you try Image>Type>8-bit and run the Keypoints detection plugin for instance

**Comment by LauLauThom** [comment]
Hmm I have the same behaviour with most plugin (except the Keypoint one).
I will try to have a look at some point.

**Comment by ghost** [comment]
I think I figured out. Keypoints plugin requires 8-bit images while the others require RGB type.

**Comment by LauLauThom** [comment]
The example plugins are mostly here for demo, ie looking at their [source code](https://github.com/joheras/IJ-OpenCV/tree/master/src/main/java/ijopencv/examples) can give you a hint of how to use the library.
The real advantage of IJ-OpenCV is that it provides converter functions between the ImageJ and OpenCV type, so you can use it to develop custom opencv scripts in ImageJ/Fiji. Also see the [wiki](https://github.com/joheras/IJ-OpenCV/wiki).

Although contributions to improve the examples are always welcome :P
